### PR TITLE
Questions & Suggestions

### PR DESCRIPTION
**Pull request by SMLMRKHLMS**
Hi @caiogondim!

Great work on this! I also appreciate the very thorough blog post. It was incredibly enlightening. After reading it, in fact, I wanted to try to implement something on my own and compare against your benchmarks. After including my own memoization method (Mark's memoized) and running the benchmark script, I got these results:

screen shot 2017-01-26 at 12 56 12 pm

I have a couple of questions regarding the above:
1. Did I incorporate my method properly into the benchmark tests?
2. If so, does my method forget important edge cases that you are accounting for?

Thanks for your time, code, and awesome blog post!

### CODE REVIEW

**Comment by caiogondim** [comment]
That's amazing.
You're missing only to check if the value is primitive or not.
In your case, if a non-primitive value is passed, it will be coerced to string will not work as key of the cache.

**Comment by caiogondim** [comment]
I'm using this function:
```js
function isPrimitive (value) {
  return value == null || (typeof value !== 'function' && typeof value !== 'object')
}
```

**Comment by SMLMRKHLMS** [comment]
@caiogondim Thanks! I really appreciate your help. I will attempt to integrate something similar and let you know what I find.

**Comment by caiogondim** [comment]
Here to help 😄 
Let me know when you're comfortable on merging your PR.

**Comment by SMLMRKHLMS** [comment]
@caiogondim I ended up integrating the primitive check into the method. I checked the method against the relevant tests within `index.text.js` and these are the results I got.

screen shot 2017-01-26 at 3 19 26 pm

Let me know what you think. Am I missing anything else? Thanks!

**Comment by caiogondim** [comment]
I would love to merge your lib in the `fast-memoize.js`
You interested on it?

In case you're, we need to pass a custom cache and serializer.
And that's it 🎉

**Comment by caiogondim** [comment]
In other words, I would like to use your code and make the tests pass without modification.
This way we don't need to release a major version.

**Comment by SMLMRKHLMS** [comment]
@caiogondim Sounds perfect! Let's do it! How would you like to proceed from here?

**Comment by SMLMRKHLMS** [comment]
@caiogondim Does your library currently pass tests if you pass an object literal `{}` as the custom cache?

**Comment by caiogondim** [comment]
It does not. 
It needs a facade with:
- `has`
- `get`
- `set`
- `delete`

Like documented here: https://github.com/caiogondim/fast-memoize.js#custom-cache

**Comment by SMLMRKHLMS** [comment]
Got it. Is there any reason why we would need to include `delete` or `has` for that matter? I only ask because when I run benchmark tests this:
```js
class Cache {
  constructor () { this.cache = Object.create(null) }
  has (key) { return (key in this.cache) }
  get (key) { return this.cache[key] }
  set (key, value) { this.cache[key] = value; return value }
  delete (key) { delete this.cache[key] }
}

function memoize(fn, options) {

  const {
    cache,
    serializer,
    monadic
  } = Object.assign({}, {
    cache: new Cache(),
    serializer: JSON.stringify,
    monadic: fn.length === 1
  }, options)

  function isPrimitive(value) { return value == null || (typeof value !== 'function' && typeof value !== 'object') }

  return function memoized(first, ...args) {
    const key = monadic && isPrimitive(first) ? first : serializer([first, ...args])
    const value = cache.get(key)
    if (value) { return value }
    return cache.set(key, fn(first, ...args))
  }
}

module.exports = memoize
```

is much faster than this:
```js
class Cache {
  constructor () { this.cache = Object.create(null) }
  get (key) { return this.cache[key] }
  set (key, value) { this.cache[key] = value }
}

function memoize(fn, options) {

  const {
    cache,
    serializer,
    monadic
  } = Object.assign({}, {
    cache: new Cache(),
    serializer: JSON.stringify,
    monadic: fn.length === 1
  }, options)

  function isPrimitive(value) { return value == null || (typeof value !== 'function' && typeof value !== 'object') }

  return function memoized(first, ...args) {
    const key = monadic && isPrimitive(first) ? first : serializer([first, ...args])
    if (cache.has(key)) { return cache.get(key) }
    const value =  fn(first, ...args)
    cache.set(key, value)
    return value
  }
}

module.exports = memoize

```

Under what circumstances would the user need `has` and `delete` do you think? Also, I have the `set` returning the value, which isn't necessary - it was just easier if I wanted it all in one line similar to `return cache[key] = fn(first, ...args)`.

**Comment by caiogondim** [comment]
Sorry for the delay.
Can you reopen the PR so we discuss about it?

**Pull request closed without merging**
