### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR adds typings for the TypeScript language, so that users will have a fully typed experience.

### CODE REVIEW

**Comment by caiogondim** [comment]
@marvinhagemeister Thanks for the PR.

To make sure we don't break the definitions, is there a way for us to do an integrity check on our test suite? (I'm not a TypeScript guy, hence the question)

**Comment by marvinhagemeister** [comment]
@caiogondim That'd be easy to add via a simple `.ts` file containing examples for `fast-memoize`. This file is then compiled by the typescript compiler and will fail automatically if there is an error.

**Comment by caiogondim** [comment]
@marvinhagemeister Would you mind adding that, so we make sure to always deliver a correct type definition?

**Comment by disintegrator** [comment]
@marvinhagemeister, @caiogondim just a heads up that the type definitions are invalid in TypeScript 2.8.3

**Comment by caiogondim** [comment]
Hi George.
Could you make a PR with a fix for it?
I'm not a TypeScript user.

**Comment by disintegrator** [comment]
Hey @caiogondim I opened #67 which adds typings and a sanity test

**Comment by caiogondim** [comment]
Closing that in favor of #67

**Pull request closed without merging**
