### PR TITLE
Adds TTL support & options - fixes #16

### LINKED ISSUE #16: Would be great to have a TTL
That way cache entries will automatically expire and not explode memory usage. This is especially important on the server.

This would likely involve you keeping a separate "shadow cache" that kept the created times of the cacheKeys. 

Obviously this would be *fractionally* slower so a simple opt-in (by say `{TTL: [any non-zero value in ms]}` in the options) to this code path is probably all you need.

### PR DESCRIPTION
**Pull request by abritinthebay**

### CODE REVIEW

**Comment by caiogondim** [comment]
Did you run the benchmark on that branch?
Can share the numbers?

**Comment by abritinthebay** [comment]
Sure! Obviously on my local machine so... not sure how that'll compare with your historical data but:

```
 vanilla  x 104,996 ops/sec ±0.75% (80 runs sampled)
 underscore  x 9,401,971 ops/sec ±1.09% (82 runs sampled)
 lodash  x 8,608,226 ops/sec ±1.38% (82 runs sampled)
 memoizee  x 9,304,963 ops/sec ±1.22% (85 runs sampled)
 addy-osmani  x 3,113,430 ops/sec ±1.48% (82 runs sampled)
 ramda  x 273,004 ops/sec ±1.16% (85 runs sampled)
 fast-memoize v2.0.2  x 8,141,253 ops/sec ±0.76% (85 runs sampled)
 strategy: Naive, cache: Map, serializer: jsonStringify  x 255,975 ops/sec ±1.05% (83 runs sampled)
 strategy: Naive, cache: Object, serializer: jsonStringify  x 225,034 ops/sec ±1.20% (82 runs sampled)
 strategy: Naive, cache: isaacs-lru-cache, serializer: jsonStringify  x 212,395 ops/sec ±1.10% (84 runs sampled)
 strategy: Optimize for single argument, cache: Map, serializer: jsonStringify  x 12,518,424 ops/sec ±0.84% (84 runs sampled)
 strategy: Optimize for single argument, cache: Object, serializer: jsonStringify  x 8,727,996 ops/sec ±1.01% (84 runs sampled)
 strategy: Optimize for single argument, cache: isaacs-lru-cache, serializer: jsonStringify  x 2,235,645 ops/sec ±1.13% (83 runs sampled)

Fastest is  strategy: Optimize for single argument, cache: Map, serializer: jsonStringify 
```

**Comment by caiogondim** [comment]
I'm OOO right now
But thinking on doing a major rewrite on the lib

The most important thing is to not do checkings on the critical path
If the user chooses to use a cache with TTL, we should provide a different memoized function
The same goes for arity `==` 1 (monadic functions), functions that returns promises, etc

Will update this thread once I'm with my computer

**Comment by abritinthebay** [comment]
That makes sense - do all the checking on the initial creation of the memoized function and then it's all set as curried data for any later call. No calculation or checks to slow it down.

FYI - thinking this implementation should use interval polling for the autoExpire checks. There are some subtle bugs I think my current implementation will create.

**Comment by caiogondim** [comment]
As I expected, your added code makes the lib slow, since it have to make more computation on the hot path.

screen shot 2016-12-05 at 8 51 48 pm

Going slower than previous versions is considered a bug, since speed is the main (and only?) goal/metric for this library.

Although, I like your idea.

As we spoke before, let's work together on porting this to the new major version of the library that I'm working on right now.

---

One interesting fact is that `Object` cache is now faster than `Map` in V8.
It is been a while since the last time I ran the benchmark and, on the last run, `Map` was faster.

I'm changing the current cache to it.

**Pull request closed without merging**
